# Generated by Django 3.2 on 2021-04-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Submission', max_length=300)),
                ('date_of_creation', models.DateField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapplic.algorithm')),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapplic.benchmark')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapplic.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapplic.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapplic.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='leaderboardAccess',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='leaderboard', to='mainapplic.leaderboard'),
        ),
        migrations.CreateModel(
            name='LeaderboardLine',
            fields=[
                ('rank', models.IntegerField()),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainapplic.submission')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapplic.leaderboard')),
            ],
        ),
    ]
